security:
  password_hashers:
    App\Entity\User: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  # ✅ IMPORTANT : Admin hérite de tout
  role_hierarchy:
    ROLE_ADMIN: [ROLE_NUTRITIONNISTE, ROLE_USER]
    ROLE_NUTRITIONNISTE: [ROLE_USER]

  firewalls:
    dev:
      pattern: ^/(_profiler|_wdt|assets|build)/
      security: false

    main:
      lazy: true
      provider: app_user_provider

      form_login:
        login_path: app_login
        check_path: app_login
        username_parameter: _username
        password_parameter: _password
        enable_csrf: true
        csrf_parameter: _csrf_token
        csrf_token_id: authenticate
        success_handler: App\Security\LoginSuccessHandler

      logout:
        path: app_logout_admin

  access_control:
    # public
    - { path: ^/Vue, roles: PUBLIC_ACCESS }
    - { path: ^/login, roles: PUBLIC_ACCESS }

    # ✅ API Chat (admin aussi grâce à role_hierarchy)
    - { path: ^/api/chat, roles: ROLE_USER }

    # front patient (admin aussi grâce à role_hierarchy)
    - { path: ^/nutrition, roles: ROLE_USER }

    # admin nutrition (nutritionniste + admin)
    - { path: ^/admin/nutrition, roles: ROLE_NUTRITIONNISTE }

    # admin dashboard
    - { path: ^/admin_dashboard, roles: ROLE_ADMIN }

    # admin global (doit être après)
    - { path: ^/admin, roles: ROLE_ADMIN }