# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    app.banned_words:
        - insultes
        - grosmot
        - interdit
        - esprit
        - violence
    app.message_encryption_enabled: true
    app.jitsi_domain: 'meet.jit.si'

services:
    _defaults:
        autowire: true      # Injection automatique des dépendances
        autoconfigure: true # Enregistre automatiquement commandes, events, etc.
        bind:
            $projectDir: '%kernel.project_dir%'
            $encryptionKey: '%env(string:MESSAGE_ENCRYPTION_KEY)%'
            $encryptionEnabled: '%app.message_encryption_enabled%'
            $jitsiDomain: '%app.jitsi_domain%'
            $hmacSecret: '%env(string:MESSAGE_ENCRYPTION_KEY)%'

    # Rend toutes les classes du dossier src/ disponibles comme services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Service personnalisé (si nécessaire)
    App\Security\LogoutSuccessHandler:
        autowire: true
        autoconfigure: true

    App\Security\AppAuthenticator:
        autowire: true
        autoconfigure: true
        arguments:
            $recaptchaSecret: '%env(string:RECAPTCHA_SECRET_KEY)%'

    App\Security\GoogleAuthenticator:
        autowire: true
        autoconfigure: true

    App\Service\ContentModerationService:
        arguments:
            $bannedWords: '%app.banned_words%'

    App\EventListener\MessageContentSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    App\Service\SmsService:
        arguments:
            $twilioAccountSid: '%env(string:TWILIO_ACCOUNT_SID)%'
            $twilioAuthToken: '%env(string:TWILIO_AUTH_TOKEN)%'
            $twilioPhone: '%env(string:TWILIO_PHONE)%'

    App\Service\EmailService:
        arguments:
            $senderEmail: '%env(string:MAILER_FROM)%'
